apply plugin: 'checkstyle'
apply plugin: 'jacoco'

jacocoTestReport {

  executionData { tasks.withType(Test).findAll { it.jacoco.destinationFile.exists() }*.jacoco.destinationFile }

  reports {
    xml.required = true
    html.required = true
  }
}

checkstyle {
  configDirectory = file("code-analysis")
  configFile = file("code-analysis/checkstyle.xml")
  maxWarnings = 0
  ignoreFailures = false
  toolVersion = "10.12.5"
}

spotless {
  java {
    target 'src/*/java/**/*.java'
    googleJavaFormat()
    removeUnusedImports()
    trimTrailingWhitespace()
    endWithNewline()
  }
}
