#!/bin/bash

echo "Running pre-commit hook"

./gradlew spotlessApply
if [ $? -ne 0 ]; then
  echo "Spotless formatting failed"
  exit 1
fi

./gradlew checkstyleMain
if [ $? -ne 0 ]; then
  echo "Checkstyle violations found, fix before commit"
  exit 1
fi

./gradlew test
if [ $? -ne 0 ]; then
  echo "Tests failed, fix before commit"
  exit 1
fi

echo "Pre-commit hook passed"
exit 0
