name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Build Project
        run: ./gradlew assemble
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run Unit Tests
        run: ./gradlew test

  docker-image-native:
    name: Docker image native
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Push Image
        uses: explorviz/deployment/.github/actions/build-and-deploy-quarkus-native@main
        with:
          platforms: "linux/amd64,linux/arm64/v8"
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: ${{ vars.DOCKER_NATIVE_IMAGE_NAME }}
          image-tag: "latest"

  docker-image-jvm:
    name: Docker image JVM
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Push Image
        uses: explorviz/deployment/.github/actions/build-and-deploy-quarkus-jvm@main
        with:
          platforms: "linux/amd64,linux/arm64/v8"
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: ${{ vars.DOCKER_JVM_IMAGE_NAME }}
          image-tag: "latest"
